Adopt for caching
a-givertzman/rust-sal-3dlib pull request #14
Opened 2024-12-27 08:49 UTC by novartole

Implement missed traits and functionality (see desc of https://github.com/a-givertzman/rust-sal-3dlib/issues/13 for details).

2025-01-20 09:41 UTC, a-givertzman requested changes
- Plese doublechek if trait Solidify it really necessary in the lib 
- Please rename:
   - crates/sal-3dlib-core/src/ops/transform.rs/Rotate::fn rotated => Rotate::fn rotate
   - crates/sal-3dlib-core/src/ops/transform.rs/Translate::fn translated => Translate::fn translate
   - and similar trades if exists and possible

2025-01-20 09:41 UTC, a-givertzman commented on crates/sal-3dlib-core/src/ops.rs
> +pub trait Solidify<A, B, C> {
Is it really necessary in the lib ?

2025-01-20 11:21 UTC, novartole commented on crates/sal-3dlib-core/src/ops.rs
> +pub trait Solidify<A, B, C> {
This trait is a wrapper over [OCCT Volume maker algorithm](https://dev.opencascade.org/doc/overview/html/specification__boolean_operations.html#specification__boolean_10b). This is a way of building result Compound from Face, Shell, and Solid sets applied together. We use this to find the underwater part of the target model.

I agree it seems too technical to make such internal algorithm public, but it's absolutely necessary for internal use. I think we could implement [Volume](https://github.com/a-givertzman/rust-sal-3dlib/blob/94b0c8129dbc3e1a3603dc7ec5a33d7122754216/crates/sal-3dlib-core/src/ops/boolean/volume.rs#L6) trait instead using Solidify algorithm in it.

2025-01-20 11:31 UTC, novartole commented
> * Please rename

I used the convention (inherited from OCCT and used in Truck) says that methods, which consume _self_ get the names ends with 'ed'. For instance,
* transformed -> creates a new instance and consume _self_ ( fn transformed(self, ... ) ),
* transform -> creates a new instance taking _self_ by reference ( fn transform(&self, ... ) ).

2025-01-26 11:32 UTC, a-givertzman approved these changes

2025-01-26 11:32 UTC, a-givertzman commented on crates/sal-3dlib-core/src/ops/boolean/volume.rs
> +/// Algorithm to volume together three sets of the objects.
This line is not enough to explain what `AlgoMakerVolume` does.
Lines below are required. But not enough again, because purpose of each of <A, B, C> - are must ti be described also.

It is general remark to most of your doc comments

2025-02-03 10:04 UTC, a-givertzman approved these changes

2025-02-03 11:08 UTC, novartole commented on crates/sal-3dlib-core/src/ops/boolean/volume.rs
> +pub trait AlgoMakerVolume<T1, T2, T3> {
added to https://github.com/a-givertzman/rust-sal-3dlib/issues/5#issuecomment-2630634522

2025-02-03 11:10 UTC, merged